# Generated by Django 4.2.11 on 2026-06-22 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='transaction',
            new_name='financial_t_type_ef0dbb_idx',
            old_name='financial_transaction_type_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='financial_t_created_dc98bb_idx',
            old_name='financial_transaction_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='financial_t_reserva_e6e896_idx',
            old_name='financial_transaction_reservation_idx',
        ),
    ]
