# Generated by Django 4.2.11 on 2026-06-29 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0013_add_reservation_archive_snapshot'),
        ('financial', '0002_rename_financial_transaction_type_idx_financial_t_type_ef0dbb_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-transaction_date', '-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='financial_t_created_dc98bb_idx',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='reference',
        ),
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('CASH', 'نقدی'), ('ACCRUAL', 'تعهدی')], default='CASH', max_length=20, verbose_name='لایه مالی'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='external_reference',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ارجاع خارجی'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CARD', 'کارت به کارت'), ('CASH', 'نقدی'), ('TRANSFER', 'انتقال بانکی'), ('POS', 'کارتخوان')], max_length=20, null=True, verbose_name='روش پرداخت'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='related_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_transactions', to='financial.transaction', verbose_name='تراکنش مرتبط'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='تاریخ تراکنش'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.BigIntegerField(verbose_name='مبلغ'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='note',
            field=models.TextField(blank=True, verbose_name='یادداشت'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='reservations.reservation', verbose_name='رزرو'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('PAYMENT', 'پرداخت'), ('DEPOSIT', 'بیعانه'), ('FINAL_PAYMENT', 'پرداخت نهایی'), ('REFUND', 'بازپرداخت'), ('DAMAGE_CHARGE', 'خسارت'), ('DAMAGE_PAYMENT', 'وصول خسارت'), ('CANCELLATION_FEE', 'جریمه لغو'), ('ADJUSTMENT', 'تعدیل دستی'), ('DISCOUNT', 'تخفیف')], max_length=20, verbose_name='نوع تراکنش'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['category'], name='financial_t_categor_b8a013_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_date'], name='financial_t_transac_088b49_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['payment_method'], name='financial_t_payment_81a389_idx'),
        ),
    ]
