"""Add reservation_snapshot JSONField to Transaction

Generated by hand to add the new field required by Transaction model changes.
"""
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0003_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reservation_snapshot',
            field=models.JSONField(blank=True, null=True, verbose_name='اسنپ‌شات مالی رزرو'),
        ),
    ]
