# Generated by Django 4.2.11 on 2026-07-05 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0014_enhance_reservation_with_snapshots'),
        ('products', '0002_alter_dress_options_alter_dress_created_at'),
        ('customers', '0005_remove_customer_created_at'),
        ('financial', '0007_add_cancellation_related_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancellationrecord',
            name='deposit_at_cancel',
            field=models.BigIntegerField(blank=True, help_text='Snapshot of deposit amount at time of cancellation', null=True, verbose_name='بیعانه در زمان لغو'),
        ),
        migrations.AlterField(
            model_name='cancellationrecord',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_record', to='reservations.reservation', verbose_name='رزرو'),
        ),
        migrations.AlterField(
            model_name='damagerecord',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_records', to='customers.customer', verbose_name='مشتری'),
        ),
        migrations.AlterField(
            model_name='damagerecord',
            name='related_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='damage_records', to='financial.transaction', verbose_name='تراکنش مرتبط'),
        ),
        migrations.AlterField(
            model_name='damagerecord',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_records', to='reservations.reservation', verbose_name='رزرو'),
        ),
        migrations.AlterField(
            model_name='guarantee',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantees', to='customers.customer', verbose_name='مشتری'),
        ),
        migrations.AlterField(
            model_name='guarantee',
            name='dress',
            field=models.ForeignKey(blank=True, help_text='Which dress this guarantee is collateral for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guarantees', to='products.dress', verbose_name='لباس'),
        ),
        migrations.AlterField(
            model_name='guarantee',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantees', to='reservations.reservation', verbose_name='رزرو'),
        ),
        migrations.AlterField(
            model_name='guarantee',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'دریافت\u200cشده'), ('RETURNED', 'بازگردانده\u200cشده'), ('FORFEITED', 'حفظ\u200cشده')], default='RECEIVED', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Direct customer link for traceability', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='customers.customer', verbose_name='مشتری'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='is_immutable',
            field=models.BooleanField(default=False, help_text='If True, cannot be edited; only reversals allowed', verbose_name='ناپذیر تغییر'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='posting_status',
            field=models.CharField(choices=[('DRAFT', 'پیش\u200cنویس'), ('POSTED', 'ثبت شده')], default='POSTED', help_text='DRAFT=tentative, POSTED=final; affects balance calculations', max_length=20, verbose_name='وضعیت ثبت'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='related_transaction',
            field=models.ForeignKey(blank=True, help_text='Links paired transactions (e.g., payment to refund)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_transactions', to='financial.transaction', verbose_name='تراکنش مرتبط'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reservation_snapshot',
            field=models.JSONField(blank=True, help_text='Immutable snapshot of reservation financial state at transaction time', null=True, verbose_name='اسنپ\u200cشات مالی رزرو'),
        ),
    ]
