# Generated by Django 4.2.11 on 2026-07-07 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


def migrate_legacy_transaction_categories(apps, schema_editor):
    Transaction = apps.get_model('financial', 'Transaction')
    TransactionCategory = apps.get_model('financial', 'TransactionCategory')

    legacy_categories = list(
        Transaction.objects.values_list('category', flat=True)
        .exclude(category__isnull=True)
        .exclude(category='')
        .distinct()
    )

    mapping = {}
    for legacy_value in legacy_categories:
        if legacy_value in ('CASH', 'ACCRUAL'):
            category_name = f'Legacy {legacy_value}'
            category_type = 'INCOME' if legacy_value == 'CASH' else 'EXPENSE'
        else:
            category_name = f'Legacy {legacy_value}'
            category_type = 'INCOME'

        legacy_category, _ = TransactionCategory.objects.get_or_create(
            name=category_name,
            defaults={'category_type': category_type, 'description': 'Migrated legacy transaction category.'},
        )
        mapping[legacy_value] = legacy_category.pk

    for legacy_value, category_pk in mapping.items():
        Transaction.objects.filter(category=legacy_value).update(category=str(category_pk))


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0014_enhance_reservation_with_snapshots'),
        ('customers', '0005_remove_customer_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_alter_dress_options_alter_dress_created_at'),
        ('financial', '0008_alter_cancellationrecord_deposit_at_cancel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='کد حساب')),
                ('name', models.CharField(max_length=200, verbose_name='نام حساب')),
                ('account_type', models.CharField(choices=[('CASH', 'صندوق'), ('BANK', 'حساب بانکی'), ('EXPENSE', 'حساب هزینه'), ('RECEIVABLE', 'حساب مطالبات')], max_length=20, verbose_name='نوع حساب')),
                ('balance', models.BigIntegerField(default=0, verbose_name='تراز فعلی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'حساب مالی',
                'verbose_name_plural': 'حساب\u200cهای مالی',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_amount', models.BigIntegerField(verbose_name='مبلغ تخصیص یافته')),
                ('allocated_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ تخصیص')),
            ],
            options={
                'verbose_name': 'تخصیص پرداخت',
                'verbose_name_plural': 'تخصیص\u200cهای پرداخت',
                'ordering': ['-allocated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reconciliation_date', django_jalali.db.models.jDateField(verbose_name='تاریخ هماهنگی')),
                ('opening_balance', models.BigIntegerField(verbose_name='تراز افتتاحی')),
                ('closing_balance', models.BigIntegerField(verbose_name='تراز اختتاح')),
                ('difference', models.BigIntegerField(verbose_name='تفاوت')),
                ('status', models.CharField(choices=[('OPEN', 'باز'), ('RESOLVED', 'حل شده'), ('IGNORED', 'نادیده گرفته شده')], default='OPEN', max_length=20)),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'ورودی هماهنگی',
                'verbose_name_plural': 'ورودی\u200cهای هماهنگی',
                'ordering': ['-reconciliation_date'],
            },
        ),
        migrations.CreateModel(
            name='TransactionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته')),
                ('category_type', models.CharField(choices=[('INCOME', 'درآمد'), ('EXPENSE', 'هزینه'), ('TRANSFER', 'انتقال'), ('ADJUSTMENT', 'تعدیل')], max_length=20, verbose_name='نوع دسته')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('color', models.CharField(default='#6c757d', max_length=7, verbose_name='رنگ')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='آیکون')),
            ],
            options={
                'verbose_name': 'دسته تراکنش',
                'verbose_name_plural': 'دسته\u200cهای تراکنش',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-transaction_date', '-created_at'], 'verbose_name': 'تراکنش', 'verbose_name_plural': 'تراکنش\u200cها'},
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='financial_t_type_ef0dbb_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='financial_t_categor_b8a013_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='financial_t_posting_b85e75_idx',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='posting_status',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='type',
        ),
        migrations.AddField(
            model_name='transaction',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تأیید'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transactions', to=settings.AUTH_USER_MODEL, verbose_name='تأییدکننده'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='financial/attachments/%Y/%m/', verbose_name='پیوست'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(default='IRR', max_length=3, verbose_name='واحد پول'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ سررسید'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_posted',
            field=models.BooleanField(default=False, verbose_name='ثبت شده'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_reconciled',
            field=models.BooleanField(default=False, verbose_name='هماهنگ شده'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_voided',
            field=models.BooleanField(default=False, editable=False, verbose_name='ابطال شده'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='یادداشت'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=200, verbose_name='کد رهگیری'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='شماره رسید'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reconciled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ هماهنگی'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_number',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True, verbose_name='شماره تراکنش'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_status',
            field=models.CharField(choices=[('DRAFT', 'پیش\u200cنویس'), ('PENDING', 'در انتظار تأیید'), ('APPROVED', 'تأیید شده'), ('POSTED', 'ثبت شده'), ('VOIDED', 'ابطال شده'), ('REVERSED', 'برگردانده شده')], default='POSTED', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'بیعانه'), ('FINAL_PAYMENT', 'پرداخت نهایی'), ('PARTIAL_PAYMENT', 'پرداخت جزئی'), ('DAMAGE_PAYMENT', 'وصول خسارت'), ('PENALTY_INCOME', 'جریمه دریافتی'), ('DAMAGE_CHARGE', 'خسارت (تعهدی)'), ('DISCOUNT', 'تخفیف'), ('PAYMENT', 'پرداخت عمومی'), ('ADJUSTMENT', 'تعدیل دستی'), ('LAUNDRY_EXPENSE', 'هزینه خشکشویی'), ('REPAIR_EXPENSE', 'هزینه تعمیر'), ('SUPPLY_EXPENSE', 'هزینه لوازم'), ('UTILITY_EXPENSE', 'هزینه\u200cهای جانبی'), ('STAFF_SALARY', 'حقوق کارمندان'), ('RENT_EXPENSE', 'هزینه اجاره'), ('MARKETING_EXPENSE', 'هزینه تبلیغات'), ('REFUND', 'بازپرداخت'), ('CANCELLATION_FEE', 'جریمه لغو'), ('TRANSFER_IN', 'انتقال ورودی'), ('TRANSFER_OUT', 'انتقال خروجی'), ('ADJUSTMENT_IN', 'تعدیل ورودی'), ('ADJUSTMENT_OUT', 'تعدیل خروجی')], db_column='transaction_type', default='DEPOSIT', max_length=30, verbose_name='نوع تراکنش'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='value_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ ارزش\u200cآفرینی'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='void_reason',
            field=models.TextField(blank=True, default='', verbose_name='دلیل ابطال'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ابطال'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_transactions', to=settings.AUTH_USER_MODEL, verbose_name='ابطال\u200cکننده'),
        ),
        migrations.AlterField(
            model_name='cancellationrecord',
            name='approval_notes',
            field=models.TextField(blank=True, default='', verbose_name='یادداشت تایید'),
        ),
        migrations.AlterField(
            model_name='cancellationrecord',
            name='deposit_at_cancel',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='بیعانه در زمان لغو'),
        ),
        migrations.AlterField(
            model_name='cancellationrecord',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='یادداشت'),
        ),
        migrations.AlterField(
            model_name='cancellationrecord',
            name='reason',
            field=models.TextField(blank=True, default='', verbose_name='دلیل لغو'),
        ),
        migrations.AlterField(
            model_name='damagerecord',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='شرح'),
        ),
        migrations.AlterField(
            model_name='damagerecord',
            name='dispute_notes',
            field=models.TextField(blank=True, default='', verbose_name='یادداشت نزاع'),
        ),
        migrations.AlterField(
            model_name='damagerecord',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='یادداشت'),
        ),
        migrations.AlterField(
            model_name='guarantee',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='شرح'),
        ),
        migrations.AlterField(
            model_name='guarantee',
            name='dress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guarantees', to='products.dress', verbose_name='لباس'),
        ),
        migrations.AlterField(
            model_name='guarantee',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='یادداشت'),
        ),
        migrations.AlterField(
            model_name='guarantee',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ بازپرداخت وجه'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transactions', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='customers.customer', verbose_name='مشتری'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='external_reference',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='ارجاع خارجی'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='is_immutable',
            field=models.BooleanField(default=False, verbose_name='ناپذیر تغییر'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='یادداشت (legacy)'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'نقدی'), ('CARD', 'کارت به کارت'), ('TRANSFER', 'انتقال بانکی'), ('POS', 'کارتخوان')], max_length=20, null=True, verbose_name='روش پرداخت'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='related_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_transactions', to='financial.transaction', verbose_name='تراکنش مرتبط'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='reservations.reservation', verbose_name='رزرو مرتبط'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reservation_snapshot',
            field=models.JSONField(blank=True, null=True, verbose_name='اسنپ\u200cشات رزرو'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sequence_number',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='شماره ترتیب'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type'], name='financial_t_transac_56d046_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_status'], name='financial_t_transac_01c3d6_idx'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='financial.financialaccount', verbose_name='حساب'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account'], name='financial_t_account_276e46_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['is_reconciled'], name='financial_t_is_reco_98df59_idx'),
        ),
        migrations.AddField(
            model_name='reconciliationentry',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='حل کننده'),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='payment_transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='financial.transaction'),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.reservation'),
        ),
        migrations.AddField(
            model_name='financialaccount',
            name='parent_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_accounts', to='financial.financialaccount', verbose_name='حساب والد'),
        ),
        migrations.RunPython(
            migrate_legacy_transaction_categories,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='financial.transactioncategory', verbose_name='دسته'),
        ),
        migrations.AddIndex(
            model_name='reconciliationentry',
            index=models.Index(fields=['reconciliation_date'], name='financial_r_reconci_9b1608_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationentry',
            index=models.Index(fields=['status'], name='financial_r_status_0c9746_idx'),
        ),
        migrations.AddIndex(
            model_name='financialaccount',
            index=models.Index(fields=['account_type'], name='financial_f_account_f73bc1_idx'),
        ),
        migrations.AddIndex(
            model_name='financialaccount',
            index=models.Index(fields=['code'], name='financial_f_code_28d23d_idx'),
        ),
    ]
