# Generated by Django 4.2.11 on 2026-07-09 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0009_financialaccount_paymentallocation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancellationrecord',
            name='refund_method',
            field=models.CharField(blank=True, choices=[('CASH', 'نقدی'), ('TRANSFER', 'انتقال بانکی'), ('POS', 'کارتخوان')], max_length=20, null=True, verbose_name='روش بازپرداخت'),
        ),
    ]
