# Generated by Django 4.2.11 on 2026-06-14 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0005_remove_customer_created_at'),
        ('products', '0002_alter_dress_options_alter_dress_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', django_jalali.db.models.jDateField(verbose_name='تاریخ شروع اجاره')),
                ('rental_days', models.PositiveIntegerField(verbose_name='مدت اجاره (روز)')),
                ('end_date', django_jalali.db.models.jDateField(editable=False, verbose_name='تاریخ پایان اجاره')),
                ('delivery_date', django_jalali.db.models.jDateField(blank=True, editable=False, null=True, verbose_name='تاریخ تحویل لباس')),
                ('event_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ مراسم')),
                ('returned_at', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ واقعی بازگشت')),
                ('rent_price', models.PositiveIntegerField(verbose_name='هزینه اجاره لباس')),
                ('deposit_amount', models.PositiveIntegerField(verbose_name='بیعانه')),
                ('discount_amount', models.PositiveIntegerField(default=0, verbose_name='تخفیف')),
                ('final_price', models.PositiveIntegerField(verbose_name='مبلغ نهایی')),
                ('remaining_amount', models.PositiveIntegerField(verbose_name='باقی مانده')),
                ('payment_method', models.CharField(choices=[('CARD', 'کارت به کارت'), ('CASH', 'نقدی'), ('TRANSFER', 'انتقال بانکی'), ('POS', 'کارتخوان')], max_length=20, verbose_name='روش پرداخت')),
                ('payment_tracking_code', models.CharField(max_length=100, verbose_name='کد رهگیری پرداخت')),
                ('guarantee1_type', models.CharField(choices=[('CHECK', 'چک'), ('CASH', 'پول'), ('GOLD', 'طلا'), ('PROMISSORY', 'سفته')], max_length=20, verbose_name='نوع ضمانت اول')),
                ('guarantee1_tracking_code', models.CharField(max_length=100, verbose_name='کد رهگیری ضمانت اول')),
                ('guarantee2_type', models.CharField(blank=True, choices=[('CHECK', 'چک'), ('CASH', 'پول'), ('GOLD', 'طلا'), ('PROMISSORY', 'سفته')], max_length=20, null=True, verbose_name='نوع ضمانت دوم')),
                ('guarantee2_tracking_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='کد رهگیری ضمانت دوم')),
                ('status', models.CharField(choices=[('DRAFT', 'پیش\u200cنویس'), ('CONFIRMED', 'قطعی'), ('DELIVERED', 'تحویل شده'), ('RETURNED', 'بازگشت داده شده'), ('LAUNDRY', 'خشکشویی'), ('CANCELLED', 'لغو شده')], default='DRAFT', max_length=20, verbose_name='وضعیت رزرو')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('cancelled_at', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ لغو')),
                ('cancellation_fee', models.PositiveIntegerField(blank=True, null=True, verbose_name='جریمه لغو')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_reservations', to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='customers.customer', verbose_name='مشتری')),
                ('dress', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='products.dress', verbose_name='لباس')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_reservations', to=settings.AUTH_USER_MODEL, verbose_name='ویرایش کننده')),
            ],
            options={
                'verbose_name': 'رزرو',
                'verbose_name_plural': 'رزروها',
                'ordering': ['-id'],
            },
        ),
    ]
