# Generated by Django 4.2.11 on 2026-05-18 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0003_alter_customer_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_days', models.PositiveSmallIntegerField(verbose_name='مدت اجاره (روز)')),
                ('rent_date', django_jalali.db.models.jDateField(verbose_name='تاریخ اجاره')),
                ('ceremony_date', django_jalali.db.models.jDateField(verbose_name='تاریخ مراسم')),
                ('return_date', django_jalali.db.models.jDateField(verbose_name='تاریخ تحویل')),
                ('payment_method', models.CharField(choices=[('POS', 'پوز'), ('CARD', 'کارت به کارت'), ('OTHER', 'سایر')], max_length=20)),
                ('payment_tracking_code', models.CharField(max_length=100)),
                ('guarantee_type_1', models.CharField(max_length=100)),
                ('guarantee_type_2', models.CharField(blank=True, max_length=100, null=True)),
                ('guarantee_tracking_code', models.CharField(max_length=100)),
                ('deposit_amount', models.PositiveIntegerField(verbose_name='بیعانه')),
                ('total_amount', models.PositiveIntegerField(verbose_name='مبلغ اجاره')),
                ('status', models.CharField(choices=[('DRAFT', 'پیش\u200cنویس'), ('CONFIRMED', 'قطعی'), ('DELIVERED', 'تحویل شده'), ('RETURNED', 'بازگشت داده شده'), ('LAUNDRY', 'خشکشویی'), ('CANCELED', 'لغو شده')], default='DRAFT', max_length=20)),
                ('product_condition', models.TextField(verbose_name='سلامت کالا')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_reservations', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='customers.customer')),
                ('dress', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='products.dress')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('DRAFT', 'پیش\u200cنویس'), ('CONFIRMED', 'قطعی'), ('DELIVERED', 'تحویل شده'), ('RETURNED', 'بازگشت داده شده'), ('LAUNDRY', 'خشکشویی'), ('CANCELED', 'لغو شده')], max_length=20)),
                ('new_status', models.CharField(choices=[('DRAFT', 'پیش\u200cنویس'), ('CONFIRMED', 'قطعی'), ('DELIVERED', 'تحویل شده'), ('RETURNED', 'بازگشت داده شده'), ('LAUNDRY', 'خشکشویی'), ('CANCELED', 'لغو شده')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='reservations.reservation')),
            ],
            options={
                'verbose_name': 'لاگ تغییر وضعیت رزرو',
                'verbose_name_plural': 'لاگ\u200cهای تغییر وضعیت رزرو',
                'ordering': ['-changed_at'],
            },
        ),
    ]
