# Generated by Django 4.2.11 on 2026-05-24 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='rent_price_snapshot',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت اجاره لباس (Snapshot)'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='total_amount',
            field=models.PositiveIntegerField(verbose_name='مبلغ اجاره نهایی'),
        ),
        migrations.DeleteModel(
            name='ReservationStatusLog',
        ),
    ]
