# Generated by Django 4.2.11 on 2026-06-14 16:11

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='end_date',
            field=django_jalali.db.models.jDateField(editable=False, verbose_name='تاریخ بازگشت'),
        ),
    ]
