# Generated by Django 4.2.11 on 2026-06-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_reservation_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'پیش\u200cنویس'), ('CONFIRMED', 'قطعی'), ('DELIVERED', 'تحویل به مشتری'), ('RETURNED', 'بازگشت از مشتری'), ('LAUNDRY', 'ارسال شده به خشکشویی'), ('READY', 'آماده و آزاد'), ('CANCELLED', 'لغو شده')], default='DRAFT', max_length=20, verbose_name='وضعیت رزرو'),
        ),
    ]
