# Generated by Django 4.2.11 on 2026-06-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservation_rent_price_snapshot_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='reservation',
            name='deposit_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='بیعانه'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='guarantee_tracking_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='guarantee_type_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('POS', 'پوز'), ('CARD', 'کارت به کارت'), ('OTHER', 'سایر')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='payment_tracking_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='product_condition',
            field=models.TextField(blank=True, verbose_name='سلامت کالا'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['status'], name='reservation_status_f1a03a_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['rent_date'], name='reservation_rent_da_aba686_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['return_date'], name='reservation_return__dd02a4_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['dress', 'status'], name='reservation_dress_i_da556f_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['customer', 'status'], name='reservation_custome_e440be_idx'),
        ),
    ]
