# Generated by Django 4.2.11 on 2026-06-18 20:48

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_alter_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='remaining_paid_at',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت باقی\u200cمانده'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='remaining_payment_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ پرداخت باقی\u200cمانده'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='remaining_payment_method',
            field=models.CharField(blank=True, choices=[('CARD', 'کارت به کارت'), ('CASH', 'نقدی'), ('TRANSFER', 'انتقال بانکی'), ('POS', 'کارتخوان')], max_length=20, null=True, verbose_name='روش پرداخت باقی\u200cمانده'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='remaining_payment_tracking_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کد رهگیری پرداخت باقی\u200cمانده'),
        ),
    ]
