# Generated by Django 4.2.11 on 2026-06-13 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_dress_options_alter_dress_created_at'),
        ('customers', '0005_remove_customer_created_at'),
        ('reservations', '0003_alter_reservation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-created_at'], 'verbose_name': 'رزرو', 'verbose_name_plural': 'رزروها'},
        ),
        migrations.RemoveIndex(
            model_name='reservation',
            name='reservation_status_f1a03a_idx',
        ),
        migrations.RemoveIndex(
            model_name='reservation',
            name='reservation_rent_da_aba686_idx',
        ),
        migrations.RemoveIndex(
            model_name='reservation',
            name='reservation_return__dd02a4_idx',
        ),
        migrations.RemoveIndex(
            model_name='reservation',
            name='reservation_dress_i_da556f_idx',
        ),
        migrations.RemoveIndex(
            model_name='reservation',
            name='reservation_custome_e440be_idx',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='guarantee_tracking_code',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='product_condition',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='reservation',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='guarantee_1_tracking_code',
            field=models.CharField(default='-', max_length=100, verbose_name='کد ضمانت اول'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='guarantee_2_tracking_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کد ضمانت دوم'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='ceremony_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ مراسم'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='customers.customer', verbose_name='مشتری'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='مبلغ بیعانه'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='products.dress', verbose_name='لباس'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='guarantee_type_1',
            field=models.CharField(choices=[('check', 'چک'), ('cash', 'پول'), ('gold', 'طلا'), ('promissory_note', 'سفته')], max_length=30, verbose_name='ضمانت اول'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='guarantee_type_2',
            field=models.CharField(blank=True, choices=[('check', 'چک'), ('cash', 'پول'), ('gold', 'طلا'), ('promissory_note', 'سفته')], max_length=30, null=True, verbose_name='ضمانت دوم'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'نقدی'), ('card', 'کارت به کارت'), ('pos', 'دستگاه کارتخوان'), ('transfer', 'حواله')], max_length=20, null=True, verbose_name='روش پرداخت'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='payment_tracking_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کد پیگیری پرداخت'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='rent_date',
            field=models.DateField(verbose_name='تاریخ شروع اجاره'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='rent_days',
            field=models.PositiveIntegerField(verbose_name='تعداد روز اجاره'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='rent_price_snapshot',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت اجاره در زمان ثبت'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='return_date',
            field=models.DateField(verbose_name='تاریخ تحویل'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('reserved', 'رزرو شده'), ('delivered', 'تحویل شده'), ('returned', 'برگشت شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت'),
        ),
    ]
