# Generated by Django on 2026-06-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_reservation_remaining_paid_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='item_damaged',
            field=models.BooleanField(default=False, verbose_name='آیا لباس آسیب‌دیده است؟'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='damage_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ خسارت'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='damage_notes',
            field=models.TextField(blank=True, verbose_name='توضیحات خسارت'),
        ),
    ]
