# Generated by Django 4.2.11 on 2026-06-21 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_add_damage_fields'),
        ('reservations', '0005_add_discount_and_refund'),
    ]

    operations = [
    ]
