# Generated by Django 4.2.11 on 2026-06-13 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_alter_dress_options_alter_dress_created_at'),
        ('reservations', '0005_reservation_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='description',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='guarantee_1_tracking_code',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='guarantee_2_tracking_code',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='guarantee_type_1',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='guarantee_type_2',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='payment_tracking_code',
        ),
        migrations.AddField(
            model_name='reservation',
            name='discount_amount',
            field=models.PositiveBigIntegerField(default=0, verbose_name='تخفیف'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='extra_charge_amount',
            field=models.PositiveBigIntegerField(default=0, verbose_name='هزینه اضافی'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='guarantee_description',
            field=models.CharField(blank=True, max_length=255, verbose_name='توضیحات ضمانت'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='guarantee_type',
            field=models.CharField(blank=True, choices=[('check', 'چک'), ('cash', 'وجه نقد'), ('gold', 'طلا'), ('promissory_note', 'سفته')], max_length=30, verbose_name='نوع ضمانت'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='notes',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='ceremony_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ مراسم'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reservations', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='deposit_amount',
            field=models.PositiveBigIntegerField(default=0, verbose_name='بیعانه'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='products.dress', verbose_name='لباس'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'نقدی'), ('card', 'کارت به کارت'), ('pos', 'پوز'), ('transfer', 'حواله')], max_length=20, verbose_name='روش پرداخت'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='rent_date',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ اجاره'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='rent_days',
            field=models.PositiveIntegerField(default=1, verbose_name='مدت اجاره (روز)'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='rent_price_snapshot',
            field=models.PositiveBigIntegerField(default=0, verbose_name='مبلغ اجاره'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='return_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ بازگشت'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('confirmed', 'تأییدشده'), ('delivered', 'تحویل\u200cشده'), ('returned', 'برگشت\u200cشده'), ('laundry', 'رختشویی'), ('canceled', 'لغوشده')], db_index=True, default='draft', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['status'], name='reservation_status_f1a03a_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['rent_date'], name='reservation_rent_da_aba686_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['ceremony_date'], name='reservation_ceremon_27682d_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['return_date'], name='reservation_return__dd02a4_idx'),
        ),
    ]
