# Generated by Django 4.2.11 on 2026-06-22 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_merge_20260621_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='discount_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='مبلغ تخفیف'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='discount_type',
            field=models.CharField(choices=[('NONE', 'بدون تخفیف'), ('AMOUNT', 'مبلغ ثابت'), ('PERCENT', 'درصد')], default='NONE', max_length=10, verbose_name='نوع تخفیف'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='discount_value',
            field=models.PositiveIntegerField(default=0, verbose_name='مقدار تخفیف'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='refunded_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='مبلغ مرجوعی'),
        ),
    ]
