# Generated by Django 4.2.11 on 2026-06-22 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_add_audit_and_soft_delete'),
        ('reservations', '0007_alter_reservation_discount_amount_and_more'),
    ]

    operations = [
    ]
