# Generated by Django 4.2.11 on 2026-06-22 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_merge_20260622_1031'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='reservation',
            new_name='reservation_status_f1a03a_idx',
            old_name='reservations_status_idx',
        ),
        migrations.RenameIndex(
            model_name='reservation',
            new_name='reservation_payment_060592_idx',
            old_name='reservations_payment_status_idx',
        ),
        migrations.RenameIndex(
            model_name='reservation',
            new_name='reservation_start_d_6ef5e1_idx',
            old_name='reservations_start_date_idx',
        ),
        migrations.RenameIndex(
            model_name='reservation',
            new_name='reservation_event_d_ab9429_idx',
            old_name='reservations_event_date_idx',
        ),
        migrations.RenameIndex(
            model_name='reservation',
            new_name='reservation_created_fddb5a_idx',
            old_name='reservations_created_at_idx',
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['is_deleted'], name='reservation_is_dele_447be6_idx'),
        ),
        migrations.AddIndex(
            model_name='reservationstatuslog',
            index=models.Index(fields=['changed_at'], name='reservation_changed_5cff84_idx'),
        ),
        migrations.AddIndex(
            model_name='reservationstatuslog',
            index=models.Index(fields=['reservation'], name='reservation_reserva_a31758_idx'),
        ),
    ]
