# Generated by Django 4.2.11 on 2026-06-29 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0009_rename_reservations_status_idx_reservation_status_f1a03a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='archived_at',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ آرشیو'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='archived_reservations', to=settings.AUTH_USER_MODEL, verbose_name='آرشیو کننده'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'پیش\u200cنویس'), ('CONFIRMED', 'قطعی'), ('DELIVERED', 'تحویل به مشتری'), ('RETURNED', 'بازگشت از مشتری'), ('LAUNDRY', 'ارسال شده به خشکشویی'), ('READY', 'آماده و آزاد'), ('CANCELLED', 'لغو شده'), ('ARCHIVED', 'آرشیو شده')], default='DRAFT', max_length=20, verbose_name='وضعیت رزرو'),
        ),
    ]
