# Generated by Django 4.2.11 on 2026-06-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0010_add_archive_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='previous_status',
            field=models.CharField(blank=True, null=True, max_length=20, verbose_name='وضعیت قبلی'),
        ),
    ]
