# Generated by Django 4.2.11 on 2026-06-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0011_add_previous_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('DRAFT', 'پیش\u200cنویس'), ('CONFIRMED', 'قطعی'), ('DELIVERED', 'تحویل به مشتری'), ('RETURNED', 'بازگشت از مشتری'), ('LAUNDRY', 'ارسال شده به خشکشویی'), ('READY', 'آماده و آزاد'), ('CANCELLED', 'لغو شده'), ('ARCHIVED', 'آرشیو شده')], max_length=20, null=True, verbose_name='وضعیت قبلی'),
        ),
    ]
