# Generated by Django 4.2.11 on 2026-07-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0014_enhance_reservation_with_snapshots'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='guarantee1_payee',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='در وجه ضمانت اول'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='guarantee2_payee',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='در وجه ضمانت دوم'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'نقدی'), ('TRANSFER', 'انتقال بانکی'), ('POS', 'کارتخوان')], max_length=20, verbose_name='روش پرداخت'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='remaining_payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'نقدی'), ('TRANSFER', 'انتقال بانکی'), ('POS', 'کارتخوان')], max_length=20, null=True, verbose_name='روش پرداخت باقی\u200cمانده'),
        ),
    ]
