# Generated by Django 4.2.11 on 2026-07-09 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0015_reservation_guarantee1_payee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان هزینه')),
                ('amount', models.PositiveIntegerField(verbose_name='مبلغ هزینه')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف نرم')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_additional_fees', to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_fees', to='reservations.reservation', verbose_name='رزرو')),
            ],
            options={
                'verbose_name': 'هزینه جانبی',
                'verbose_name_plural': 'هزینه\u200cهای جانبی',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reservation'], name='reservation_reserva_169cfb_idx'), models.Index(fields=['created_at'], name='reservation_created_c86a51_idx'), models.Index(fields=['is_deleted'], name='reservation_is_dele_0978b4_idx')],
            },
        ),
    ]
