# Generated by Django 4.2.11 on 2026-07-09 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0016_additionalfee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='payment_method',
            field=models.CharField(choices=[('CARD', 'کارت به کارت'), ('CASH', 'نقدی'), ('TRANSFER', 'انتقال بانکی'), ('POS', 'کارتخوان')], max_length=20, verbose_name='روش پرداخت'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='remaining_payment_method',
            field=models.CharField(blank=True, choices=[('CARD', 'کارت به کارت'), ('CASH', 'نقدی'), ('TRANSFER', 'انتقال بانکی'), ('POS', 'کارتخوان')], max_length=20, null=True, verbose_name='روش پرداخت باقی\u200cمانده'),
        ),
    ]
