# Generated by Django 4.2.11 on 2026-07-09 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0017_alter_reservation_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'نقدی'), ('TRANSFER', 'انتقال بانکی'), ('POS', 'کارتخوان')], max_length=20, verbose_name='روش پرداخت'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='remaining_payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'نقدی'), ('TRANSFER', 'انتقال بانکی'), ('POS', 'کارتخوان')], max_length=20, null=True, verbose_name='روش پرداخت باقی\u200cمانده'),
        ),
    ]
