# Generated by Django 4.2.11 on 2026-07-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0018_alter_reservation_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='tailor_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='نام خیاط'),
        ),
    ]
