# Generated by Django 4.2.11 on 2026-07-10 09:46

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0019_reservation_tailor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='cancellation_fee_paid_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='مبلغ پرداخت شده جریمه لغو'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='cancellation_fee_paid_at',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='زمان پرداخت جریمه لغو'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='cancellation_fee_payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'نقدی'), ('TRANSFER', 'انتقال بانکی'), ('POS', 'کارتخوان')], max_length=20, null=True, verbose_name='روش پرداخت جریمه لغو'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='cancellation_fee_tracking_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کد رهگیری پرداخت جریمه لغو'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='damage_fee_paid_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='مبلغ پرداخت شده جریمه خسارت'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='damage_fee_paid_at',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='زمان پرداخت جریمه خسارت'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='damage_fee_payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'نقدی'), ('TRANSFER', 'انتقال بانکی'), ('POS', 'کارتخوان')], max_length=20, null=True, verbose_name='روش پرداخت جریمه خسارت'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='damage_fee_tracking_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کد رهگیری پرداخت جریمه خسارت'),
        ),
    ]
