# Generated by Django 4.2.11 on 2026-07-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0020_reservation_cancellation_fee_paid_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='contract_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='شماره قرارداد'),
        ),
    ]
