# Generated by Django 4.2.11 on 2026-07-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0021_add_contract_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='guarantee1_tracking_code',
            field=models.CharField(blank=True, max_length=100, verbose_name='کد رهگیری ضمانت اول'),
        ),
    ]
