# reservations/constants.py
RESERVATION_TRANSITIONS = {
    'DRAFT': ('CONFIRMED', 'CANCELED'),
    'CONFIRMED': ('DELIVERED', 'CANCELED'),
    'DELIVERED': ('RETURNED',),
    'RETURNED': ('LAUNDRY',),
    'LAUNDRY': (),
    'CANCELED': (),
}

AVAILABILITY_BLOCKING_STATUSES = {
    'CONFIRMED',
    'DELIVERED',
}

TERMINAL_RESERVATION_STATUSES = {
    'LAUNDRY',
    'CANCELED',
}

INVENTORY_RELEASED_STATUSES = {
    'RETURNED',
    'LAUNDRY',
    'CANCELED',
}
