RESERVATION_STATUS_PENDING = 'pending'
RESERVATION_STATUS_RESERVED = 'reserved'
RESERVATION_STATUS_DELIVERED = 'delivered'
RESERVATION_STATUS_RETURNED = 'returned'
RESERVATION_STATUS_CANCELLED = 'cancelled'

RESERVATION_TRANSITIONS = {
    RESERVATION_STATUS_PENDING: [
        RESERVATION_STATUS_RESERVED,
        RESERVATION_STATUS_CANCELLED,
    ],
    RESERVATION_STATUS_RESERVED: [
        RESERVATION_STATUS_DELIVERED,
        RESERVATION_STATUS_CANCELLED,
    ],
    RESERVATION_STATUS_DELIVERED: [
        RESERVATION_STATUS_RETURNED,
    ],
    RESERVATION_STATUS_RETURNED: [],
    RESERVATION_STATUS_CANCELLED: [],
}
