# Generated by Django 4.2.11 on 2026-05-18 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bride_first_name', models.CharField(max_length=50, verbose_name='نام عروس')),
                ('bride_last_name', models.CharField(max_length=50, verbose_name='نام خانوادگی عروس')),
                ('bride_phone', models.CharField(max_length=15, verbose_name='شماره تماس عروس')),
                ('ceremony_date', models.DateField(verbose_name='تاریخ مراسم')),
                ('how_to_know', models.CharField(max_length=100, verbose_name='نحوه آشنایی')),
                ('allow_contact', models.BooleanField(default=False, verbose_name='اجازه ارتباط با شما؟')),
                ('groom_first_name', models.CharField(blank=True, max_length=50, verbose_name='نام داماد')),
                ('groom_last_name', models.CharField(blank=True, max_length=50, verbose_name='نام خانوادگی داماد')),
                ('groom_phone', models.CharField(blank=True, max_length=15, verbose_name='شماره تماس داماد')),
                ('requested_services', models.TextField(blank=True, verbose_name='خدمات مورد نظر')),
                ('estimated_budget', models.PositiveIntegerField(blank=True, null=True, verbose_name='بودجه تقریبی مدنظر (تومان)')),
                ('additional_services', models.TextField(blank=True, verbose_name='خدمات جانبی مورد نیاز')),
                ('preferred_consultant', models.CharField(blank=True, max_length=50, verbose_name='ترجیح می\u200cدهم مشاوره من توسط:')),
                ('guest_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد تقریبی مهمان')),
                ('ceremony_decoration', models.CharField(blank=True, max_length=100, verbose_name='تشریفات')),
                ('beauty_salon', models.CharField(blank=True, max_length=100, verbose_name='اسم سالن زیبایی')),
                ('studio_name', models.CharField(blank=True, max_length=100, verbose_name='آتلیه')),
                ('music_band', models.CharField(blank=True, max_length=100, verbose_name='گروه موسیقی')),
                ('customer_note', models.TextField(blank=True, verbose_name='یادداشت مشتری')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر ثبت\u200cکننده')),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتریان',
                'ordering': ['ceremony_date'],
            },
        ),
    ]
