# Generated by Django 4.2.11 on 2026-05-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='additional_services',
            field=models.CharField(blank=True, max_length=50, verbose_name='خدمات جانبی مورد نیاز'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='estimated_budget',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='بودجه تقریبی مدنظر (تومان)'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='requested_services',
            field=models.CharField(blank=True, max_length=50, verbose_name='خدمات مورد نظر'),
        ),
    ]
