# Generated by Django 4.2.11 on 2026-05-18 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_additional_services_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['ceremony_date'], 'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
    ]
