# Generated by Django 4.2.11 on 2026-06-09 10:47

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='ceremony_date',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ مراسم'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت'),
        ),
    ]
