# Generated by Django 4.2.11 on 2026-07-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_remove_customer_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='شهر'),
        ),
    ]
