# Generated by Django 4.2.11 on 2026-05-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد لباس')),
                ('daily_rent_price', models.PositiveIntegerField(verbose_name='قیمت اجاره روزانه (تومان)')),
                ('status', models.CharField(choices=[('ACTIVE', 'فعال')], default='ACTIVE', editable=False, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
