# Generated by Django 4.2.11 on 2026-06-10 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dress',
            options={'ordering': ['-id'], 'verbose_name': 'لباس', 'verbose_name_plural': 'لباس\u200cها'},
        ),
        migrations.AlterField(
            model_name='dress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت'),
        ),
    ]
